web:
  build: ./backend
  command: python3 manage.py runserver
  ports:
    - "5000:5000"
  volumes:
    - ./backend:/src
  links:
    - db
db:
  image: mongo:3.0.2
  volumes:
    - ./db:/data/db
  ports:
    - "27017:27017"
frontend:
  build: ./frontend
  ports:
    - "80:80"
  links:
    - web
